# Generated by Django 4.1 on 2023-08-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='level_of_expertise',
            field=models.IntegerField(default=0),
        ),
    ]
