# Generated by Django 4.1 on 2023-08-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_info',
        ),
    ]
